
# Variables


| pos  | variable | label | Reverse | Component of Scale | col_type | missing | levels | value_labels |
| ---  | -------- | ----- | ------- | ------------------ | -------- | ------- | ------ | ------------ |
| 1    | StartDate | Start Date  |         |  | dttm     | 0       | NULL   | NULL  |
| 2    | EndDate                | End Date  |         |                    | dttm     | 0       | NULL   | NULL |
| 3    | Status                 | Response Type    |         |                    | dbl+lbl  | 0       | NULL   | 0, 1, 2, 4, 8, 9, 12, 16, 17, 32, 40, 48 |
| 4    | Progress               | Progress  |         |                    | dbl      | 0       | NULL   | NULL                                     |
| 5    | Duration\_*in_seconds* | Duration (in seconds)  |         |                    | dbl      | 0       | NULL   | NULL  |
| 6    | Finished               | Finished  |         |                    | dbl+lbl  | 0       | NULL   | 0, 1   |
| 7    | RecordedDate           | Recorded Date |         |                    | dttm     | 0       | NULL   | NULL  |
| 8    | ResponseId             | Response ID  |         |                    | chr      | 0       | NULL   | NULL  |
| 9    | DistributionChannel    | Distribution Channel |         |                    | chr      | 0       | NULL   | NULL |
| 10   | UserLanguage           | User Language |         |                    | chr      | 0       | NULL   | NULL |
| 11   | Q_RecaptchaScore       | Q_RecaptchaScore |         |                    | dbl      | 0       | NULL   | NULL  |
| 12   | ConsentForm            | Study Title: Perceptions of Communicated Information |         |                    | dbl+lbl  | 0       | NULL   | 1, 2 |
| 13   | AgentNameCheck         | Which of these was the name of the author for the blog post you read? |         |          | dbl+lbl  | 2       | NULL   | 1, 2, 3, 6, 5, 4  |
| 14   | AgentTypeCheck         | What was the author?  |         |                    | dbl+lbl  | 2       | NULL   | 1, 2  |
| 15   | TopicCheck             | What was the blog post that you read about? |         |                    | dbl+lbl  | 2       | NULL   | 1, 2, 3                                  |
| 16   | GodspeedMETI_1         | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Fake \| Natural                    |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 17   | GodspeedMETI_2         | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Machinelike \| Humanlike           |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 18   | GodspeedMETI_3         | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Unconscious \| Conscious           |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 19   | GodspeedMETI_4         | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Artificial \| Lifelike             |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 20   | GodspeedMETI_5         | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Dislike \| Like                    |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 21   | GodspeedMETI_6         | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Unfriendly \| Friendly             |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 22   | GodspeedMETI_7         | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Unkind \| Kind                     |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 23   | GodspeedMETI_8         | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Unpleasant \| Pleasant             |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 24   | GodspeedMETI_9         | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Awful \| Nice                      |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 25   | GodspeedMETI_10        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Incompetent \| Competent           |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 26   | GodspeedMETI_11        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Ignorant \| Knowledgeable          |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 27   | GodspeedMETI_12        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Irresponsible \| Responsible       |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 28   | GodspeedMETI_13        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Unintelligent \| Intelligent       |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 29   | GodspeedMETI_14        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Foolish \| Sensible                |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 30   | GodspeedMETI_15        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Well Educated \| Poorly Educated   |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 31   | GodspeedMETI_16        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Professional \| Unprofessional     |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 32   | GodspeedMETI_17        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Experienced \| Inexperienced       |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 33   | GodspeedMETI_18        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Qualified \| Unqualified           |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 34   | GodspeedMETI_19        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Sincere \| Insincere               |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 35   | GodspeedMETI_20        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Honest \| Dishonest                |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 36   | GodspeedMETI_21        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Just \| Unjust                     |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 37   | GodspeedMETI_22        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Fair \| Unfair                     |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 38   | GodspeedMETI_23        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Moral \| Immoral                   |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 39   | GodspeedMETI_24        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Ethical \| Unethical               |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 40   | GodspeedMETI_25        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Responsible \| Irresponsible       |         |                    | dbl      | 4       | NULL   | NULL                                     |
| 41   | GodspeedMETI_26        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Considerate \| Inconsiderate       |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 42   | GodspeedMETI_28        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Set the slider to the far right \| |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 43   | GodspeedMETI_29        | Thinking of the author for the blog post you’ve just read, set the slider to the appropriate level between each pair of adjectives. Do not spend too much time on each item, answer with your first instinct. - Set the slider to the far left \|  |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 44   | Appelman_1             | accurate  |         |                    | dbl      | 4       | NULL   | NULL                                     |
| 45   | Appelman_2             | authentic |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 46   | Appelman_3             | believable |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 47   | Appelman_4             | well-written |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 48   | Appelman_5             | boring  |         |                    | dbl      | 4       | NULL   | NULL                                     |
| 49   | Appelman_6             | engaging |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 50   | TrustBehaviour_1       | If I were to suffer from a relevant medical condition, I am likely to use Velocerin. |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 51   | TrustBehaviour_2       | I would share the information in the article with a close friend or family member who may benefit from the medication described.   |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 52   | TrustBehaviour_3       | I believe the claims made about Velocerin in this article. |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 53   | TrustBehaviour_4       | I do not have confidence in Velocerin based on what I have read. |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 54   | TrustBehaviour_5       | The blog post is not trustworthy enough for me to share on social media, if I were a person who shares links on social media.   |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 55   | TrustBehaviour_6       | If I were suffering from a relevant medical condition, I would look into Velocerin more after reading this blog post.  |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 56   | TrustBehaviour_7       | I would ask the author of this blog post to summarize scientific content for me in the future.  |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 57   | TrustBehaviour_8       | I would read articles by the author of this blog post in the future if they were on a topic that was of interest to me.  | dbl      | 3       | NULL   | NULL  |
| 58   | TrustBehaviour_9       | After reading this blog post I have enough information to make an informed decision about Velocerin.  |         |                    | dbl      | 3       | NULL   | NULL                                     |
| 59   | AIChatbotsFrequency    | How often do you use generative AI chatbots, such as ChatGPT, Claude, Gemini, Copilot, or Grok?  |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5, 6, 7, 8                   |
| 60   | ScienceContent         | How often do you consume media similar to what was presented in the blog post?  |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5, 6, 7, 8                   |
| 61   | AIChatbotsUsed_1       | Which generative AI chatbots have you used? ChatGPT |         |                    | dbl+lbl  | 49      | NULL   | 1                                        |
| 62   | AIChatbotsUsed_2       | Which generative AI chatbots have you used? Claude  |         |                    | dbl+lbl  | 292     | NULL   | 1                                        |
| 63   | AIChatbotsUsed_3       | Which generative AI chatbots have you used? Gemini |         |                    | dbl+lbl  | 209     | NULL   | 1                                        |
| 64   | AIChatbotsUsed_4       | Which generative AI chatbots have you used? Copilot |         |                    | dbl+lbl  | 217     | NULL   | 1                                        |
| 65   | AIChatbotsUsed_5       | Which generative AI chatbots have you used? Grok |         |                    | dbl+lbl  | 301     | NULL   | 1                                        |
| 66   | AIChatbotsUsed_7       | Which generative AI chatbots have you used? Other  |         |                    | dbl+lbl  | 296     | NULL   | 1                                        |
| 67   | AIChatbotsUsed_8       | Which generative AI chatbots have you used? None |         |                    | dbl+lbl  | 285     | NULL   | 1                                        |
| 68   | Experience_1           | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I intend to use a generative AI chatbot in the future.                                                                                |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 69   | Experience_2           | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I would ask a generative AI chatbot to summarize scientific information for me.                                                       |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 70   | Experience_3           | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I would ask a generative AI chatbot to create non-scientific content for me.                                                          |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 71   | Experience_4           | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - The content I read today has changed my opinion on generative AI chatbots.                                                            |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 72   | Experience_5           | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I am afraid of generative AI chatbots as they exist today.                                                                            |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 73   | Experience_6           | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I am afraid of the potential future of generative AI.                                                                                 |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 74   | Experience_7           | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I could write content similar to the blog post I read in this study.                                                                  |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 75   | Experience_8           | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I have a strong background in science.                                                                                                |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 76   | Experience_9           | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I have professional experience related to the content of the blog post in the study.                                                  |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 77   | Experience_10          | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I have professional experience writing content.                                                                                       |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 78   | Experience_11          | On a scale from Strongly disagree to Strongly agree indicate how much you agree with the statements below. - I have professional experience in a communication related field.                                                                      |         |                    | dbl+lbl  | 3       | NULL   | 1, 2, 3, 4, 5                            |
| 79   | Age_1                  | How old are you? - Age  |         |                    | dbl      | 4       | NULL   | NULL  |
| 80   | Gender                 | How do you describe yourself? - Selected Choice  |    |   | dbl+lbl  | 4       | NULL   | 1 (Non-binary), 2 (Man), 3 (Woman), 4 (Prefer to self describe), 5 (Prefer not to say)  |
| 81   | Gender_4_TEXT          | How do you describe yourself? - Prefer to self-describe - Text |         |                    | chr      | 0       | NULL   | NULL     |
| 82   | Sex                    | Sex assigned at birth?  |         |                    | dbl+lbl  | 4       | NULL   | 1, 2, 3, 4 |
| 83   | English                | Was English your first language learned at home in childhood?   |         |                    | dbl+lbl  | 4       | NULL   | 1, 2, 3                                  |
| 84   | Languages_1            | Which languages do you speak fluently? (Check all that apply) - Selected Choice English   |         |                    | dbl+lbl  | 6       | NULL   | 1                                        |
| 85   | Languages_2            | Which languages do you speak fluently? (Check all that apply) - Selected Choice Mandarin  |         |                    | dbl+lbl  | 312     | NULL   | 1                                        |
| 86   | Languages_3            | Which languages do you speak fluently? (Check all that apply) - Selected Choice Hindi    |         |                    | dbl+lbl  | 316     | NULL   | 1                                        |
| 87   | Languages_4            | Which languages do you speak fluently? (Check all that apply) - Selected Choice Spanish |         |                    | dbl+lbl  | 302     | NULL   | 1                                        |
| 88   | Languages_5            | Which languages do you speak fluently? (Check all that apply) - Selected Choice French   |         |                    | dbl+lbl  | 315     | NULL   | 1                                        |
| 89   | Languages_6            | Which languages do you speak fluently? (Check all that apply) - Selected Choice Arabic    |         |                    | dbl+lbl  | 317     | NULL   | 1                                        |
| 90   | Languages_7            | Which languages do you speak fluently? (Check all that apply) - Selected Choice Bengali   |         |                    | dbl+lbl  | 317     | NULL   | 1                                        |
| 91   | Languages_8            | Which languages do you speak fluently? (Check all that apply) - Selected Choice Portuguese |         |                    | dbl+lbl  | 317     | NULL   | 1                                        |
| 92   | Languages_9            | Which languages do you speak fluently? (Check all that apply) - Selected Choice Russian   |         |                    | dbl+lbl  | 317     | NULL   | 1                                        |
| 93   | Languages_10           | Which languages do you speak fluently? (Check all that apply) - Selected Choice Urdu  |         |                    | dbl+lbl  | 317     | NULL   | 1                                        |
| 94   | Languages_11           | Which languages do you speak fluently? (Check all that apply) - Selected Choice Other (please list)  |         |                    | dbl+lbl  | 310     | NULL   | 1                                        |
| 95   | Languages_12           | Which languages do you speak fluently? (Check all that apply) - Selected Choice Prefer not to say  |         |                    | dbl+lbl  | 315     | NULL   | 1                                        |
| 96   | Languages_11_TEXT      | Which languages do you speak fluently? (Check all that apply) - Other (please list) - Text |         |                    | chr      | 0       | NULL   | NULL                                     |
| 97   | Education              | Level of Education completed (Canada)   |         |                    | dbl+lbl  | 4       | NULL   | 1, 2, 3, 4, 5, 6, 7, 8, 9                |
| 98   | Unrealistic            | Did any parts of this survey seem unrealistic or confusing to you, and if so, which ones? - Selected Choice  |         |                    | dbl+lbl  | 4       | NULL   | 1, 2                                     |
| 99   | Unrealistic_2_TEXT     | Did any parts of this survey seem unrealistic or confusing to you, and if so, which ones? - Yes - Text   |         |                    | chr      | 0       | NULL   | NULL                                     |
| 100  | TechnicalIssues        | Did you experience any technical issues or interruptions during this experiment? |         |                    | dbl+lbl  | 4       | NULL   | 1, 2                                     |
| 101  | SurveyTopicCheck       | In approximately 1 sentence, please tell us what you think this study is about. |         |                    | chr      | 0       | NULL   | NULL                                     |
| 102  | id                     | id  |         |                    | chr      | 0       | NULL   | NULL                                     |
| 103  | Condition              | Condition  |         |                    | chr      | 0       | NULL   | NULL                                     |
| 104  | Reread                 | Reread  |         |                    | chr      | 0       | NULL   | NULL                                     |
| 105  | completion_code        | completion_code  |         |                    | chr      | 0       | NULL   | NULL                                     |

