
Analysis of Variance of `r y_label` by `r x_label`

Let's try with an ANOVA
```{r}
library(apa)
library(effectsize)
library(rstatix)

options(es.use_symbols = TRUE) # get nice symbols when printing! (On Windows, requires R >= 4.2.0)
```

```{r}

result <- tryCatch({
    # Code produces error
    aov_model <- aov(formula = formula, data = data)
    model_summ <- summary(aov_model)
    
    model_summ
    
    return(model_summ)
    
  }, error = function(e) {
    # Handle the error
    cat("An error occurred:", e$message, "\n")
    return(NA)
  })


```


```{r}

result <- tryCatch({
    # Code produces error
    anova_apa(aov_model)
    
  }, error = function(e) {
    # Handle the error
    cat("An error occurred:", e$message, "\n")
    return(NA)
  })



```


```{r}
# Between group MSE.
print(paste0("MSE = ", model_summ[[1]]["Mean Sq"][[1]][1]))
```

```{r}

effectsize::omega_squared(aov_model)

```


Follow-up tests to identify where variance is located

```{r}



# Error handling using tryCatch
result <- tryCatch({
  # Code produces error
  rstatix::pairwise_t_test(data = data, formula = formula,  p.adjust.method = "bonferroni", detailed = TRUE, paired = FALSE)
}, error = function(e) {
  # Handle the error
  cat("An error occurred:", e$message, "\n")
  return(NA)
})

result

```

```{r}



# Error handling using tryCatch
result <- tryCatch({
  # Code produces error
  rstatix::t_test(data = data, formula = formula,  p.adjust.method = "bonferroni", detailed = TRUE, paired = FALSE)
}, error = function(e) {
  # Handle the error
  cat("An error occurred:", e$message, "\n")
  return(NA)
})

result

```


```{r}
# Error handling using tryCatch
result <- tryCatch({
  # Code produces error
  rstatix::cohens_d(data = data, formula = formula)
}, error = function(e) {
  # Handle the error
  cat("An error occurred:", e$message, "\n")
  return(NA)
})

result
```

But we should test assumptions for the ANOVA before we use these results

First test for normality

```{r}

plot(aov_model)

# Test for Normality
hist(y)

qqnorm(aov_model$residuals)
qqline(aov_model$residuals)

shapiro.test(y)
```

Next test for equal variance

```{r}
# Test for Equal Variance
boxplot(formula, xlab = x_label, ylab = y_label, data = data)

result <- tryCatch({
  # Code produces error
  bartlett.test(formula, data = data)
}, error = function(e) {
  # Handle the error
  cat("An error occurred:", e$message, "\n")
  return(NA)
})

```

